### ISSUE TITLE
compiler

### ISSUE THREAD

**Issue by Swayz3** [rtldg/mpbhops_but_working#1]
could you upload a compiled version, keeps throwing errors for line 183 when I try to compile

**Comment by rtldg** [comment]
can you post the error because it doesn't look like there's anything wrong with line 183

**Comment by Swayz3** [comment]
sure
 //// mpbhops_but_working.sp
//
// mpbhops_but_working.sp(10) : fatal error 183: cannot read from file: "shavit/core"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.08 sec

**Comment by rtldg** [comment]
download the bhoptimer scripting files and then try to compile or disable bhoptimer support by changing the `1` to a `0` on line 8

**Comment by Swayz3** [comment]
thank you so much been trying to fix boosters for a long time.

**Comment by Swayz3** [comment]
yea it worked, don't know why I didn't try that earlier

**Comment by rtldg** [comment]
np np
